Repository Space-Club/Backend, pull requests merged in 2023-11, with the labels that each got.

#56 [SKRB-211] feat: 클럽 행사 조회하기 API 구현
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubEventGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/controller/dto/ClubEventGetResponseTest.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/repository/EventRepositoryTest.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
  src/test/resources/application.yml
Labels: FEAT

#58 [SKRB-196] feat: 행사 상세 조회 + rest docs 작성
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/FormInfo.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#60 [SKRB-204] feat: 클럽 멤버 권한 수정 API 틀 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubUserUpdateRequest.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/domain/ClubUserRole.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/vo/ClubUserUpdate.java
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
Labels: FEAT

#61 [SKRB-204] feat: 클럽 멤버 권한 수정 API 구현, 테스트 작성
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/vo/ClubUserUpdate.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/repository/ClubUserRepositoryTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
  src/test/java/com/spaceclub/user/UserTestFixture.java
Labels: FEAT

#63 [SKRB-212] feat: 클럽 멤버 조회 api 틀 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/MemberGetResponse.java
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
Labels: FEAT

#64 [SKRB-225] feat: 클럽 멤버 조회 API 구현 및 테스트 작성
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/MemberGetResponse.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/user/domain/RequiredInfo.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/ClubUserTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/repository/ClubUserRepositoryTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
  src/test/java/com/spaceclub/user/UserTestFixture.java
Labels: FEAT

#70 fix: deploy.sh 프로젝트 이름 변경
  scripts/deploy.sh
Labels: bug

#69 [SRKB-242] feat: log 생성 관련 deploy.sh 설정
  scripts/deploy.sh
Labels: documentation, FEAT

#65 [SKRB-234] feat: 초대 링크 URL 형태로 변경, 초대 테이블을 Club 테이블의 필드로 변경
  src/main/java/com/spaceclub/club/InvitationCodeGenerator.java
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubCreateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/domain/Invitation.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: enhancement

#66 [SKRB-206] feat: 클럽 멤버 탈퇴하기 API 구현 및 테스트 작성
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/ClubUserTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/repository/ClubUserRepositoryTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
Labels: FEAT

#72 [SKRB-199] fix: 초대 링크 생성시 NPE 발생 문제 해결
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/resources/local/application-local.yml
Labels: bug

#76 [SKRB-230] docs: 초대 링크 생성, 초대 링크를 통한 클럽 가입 api 명세
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: documentation

#71 [SKRB-205] feat: 클럽 목록 보기 API 구현 및 테스트 작성
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/ClubGetAllResponse.java
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/repository/ClubUserRepositoryTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
Labels: FEAT

#78 [SKRB-196] docs: 행사 상세 조회 api 명세 추가
  src/docs/asciidoc/event-api.adoc
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: documentation

#79 [SKRB-208] feat: 클럽 조회 API 구현 및 테스트 작성
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#81 [hotfix] feat: 클럽 생성시 응답 헤더 location 값 구성 변경
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: enhancement

#86 [SKRB-230] feat: Location 포함 헤더 노출 설정
  src/main/java/com/spaceclub/global/config/WebConfig.java
Labels: enhancement

#87 [SKRB-252] feat: 유저 로그인 및 조회 추가 구현
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/global/jwt/service/JwtService.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserCodeRequest.java
  src/main/java/com/spaceclub/user/domain/PhoneNumber.java
  src/main/java/com/spaceclub/user/domain/RequiredInfo.java
  src/main/java/com/spaceclub/user/repository/UserRepository.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/main/resources/local/application-oauth.yml
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#88 [SKRB-226] feat: 토큰 헤더 적용 및 유저의 클럽 조회 API 도메인 이동
  src/docs/asciidoc/club-api.adoc
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventApplyRequest.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
  src/test/java/com/spaceclub/user/service/UserServiceTest.java
Labels: FEAT

#93 [SKRB-230] feat: 초대 링크 생성, 초대 링크를 통한 클럽 가입, docs 최신화
  src/main/java/com/spaceclub/club/InvitationCodeGenerator.java
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Invitation.java
  src/main/java/com/spaceclub/club/repository/ClubRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#38 [SKRB-149] feat: Event 엔티티 유효성 검사 구현 및 테스트
  src/main/java/com/spaceclub/event/domain/BankInfo.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/domain/FormInfo.java
  src/main/java/com/spaceclub/event/domain/TicketInfo.java
  src/test/java/com/spaceclub/event/domain/BankInfoTest.java
  src/test/java/com/spaceclub/event/domain/EventInfoTest.java
  src/test/java/com/spaceclub/event/domain/EventTest.java
  src/test/java/com/spaceclub/event/domain/FormInfoTest.java
  src/test/java/com/spaceclub/event/domain/TicketInfoTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#97 fix: EventInfo 엔티티 상수 static 설정
  src/main/java/com/spaceclub/event/domain/EventInfo.java
Labels: bug

#98 fix: 유저가 신청한 행사 조회 adoc 수정
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: bug

#95 [SKRB-254] feat: S3 이미지, 초대코드 URL 처리
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/ClubGetAllResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/event/controller/dto/EventGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/global/S3ImageUploader.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserClubGetResponse.java
  src/main/java/com/spaceclub/user/controller/dto/UserEventGetResponse.java
  src/main/resources/application.yml
  src/main/resources/global/application-s3.yml
  src/main/resources/local/application-local.yml
Labels: FEAT

#99 fix: application-oauth.yml 폴더 이동
  src/main/resources/global/application-oauth.yml
Labels: bug

#96 feat: 클럽 생성 토큰 적용
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubCreateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
Labels: FEAT

#100 [SKRB-256] refactor: 초대 링크 도메인 분리, docs 반영
  src/docs/asciidoc/club-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/invite-api.adoc
  src/main/java/com/spaceclub/club/InvitationCodeGenerator.java
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubCreateRequest.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/domain/Invitation.java
  src/main/java/com/spaceclub/club/repository/ClubRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/invite/domain/Invite.java
  src/main/java/com/spaceclub/invite/domain/InviteCodeGenerator.java
  src/main/java/com/spaceclub/invite/domain/UuidCodeGenerator.java
  src/main/java/com/spaceclub/invite/repository/InviteRepository.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/main/resources/local/application-local.yml
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
Labels: REFACTOR

#102 [SKRB-292] feat: Form 관련 엔티티, Controller, Service, Repository 생성
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/domain/Form.java
  src/main/java/com/spaceclub/form/domain/FormItem.java
  src/main/java/com/spaceclub/form/domain/FormItemUser.java
  src/main/java/com/spaceclub/form/repository/FormItemRepository.java
  src/main/java/com/spaceclub/form/repository/FormItemUserRepository.java
  src/main/java/com/spaceclub/form/repository/FormRepository.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/user/domain/User.java
Labels: FEAT

#103 [SKRB-290] feat: 3차 테스트 목표 API 틀 구현 및 Restdocs 구현
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/form-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationCreateRequest.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationGetResponse.java
  src/main/java/com/spaceclub/form/controller/dto/FormCreateRequest.java
  src/main/java/com/spaceclub/form/controller/dto/FormGetResponse.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#104 [SKRB-288] feat: 행사 폼 양식 생성하기 API 구현
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormCreateRequest.java
  src/main/java/com/spaceclub/form/domain/Form.java
  src/main/java/com/spaceclub/form/domain/FormItem.java
  src/main/java/com/spaceclub/form/domain/FormOption.java
  src/main/java/com/spaceclub/form/domain/FormOptionType.java
  src/main/java/com/spaceclub/form/domain/FormOptionUser.java
  src/main/java/com/spaceclub/form/repository/FormItemRepository.java
  src/main/java/com/spaceclub/form/repository/FormItemUserRepository.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/vo/FormCreate.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#107 [SKRB-289] feat: 행사 폼 양식 조회하기 API 구현
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormGetResponse.java
  src/main/java/com/spaceclub/form/domain/Form.java
  src/main/java/com/spaceclub/form/domain/FormOption.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/vo/FormGet.java
  src/test/java/com/spaceclub/form/FormTestFixture.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#108 [SKRB-283] feat: 폼 제출을 통한 행사 신청하기 API 구현
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationCreateRequest.java
  src/main/java/com/spaceclub/form/domain/FormOptionUser.java
  src/main/java/com/spaceclub/form/repository/FormOptionRepository.java
  src/main/java/com/spaceclub/form/repository/FormOptionUserRepository.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#105 [SKRB-201] feat: 클럽 초대 링크 만료 여부 확인 구현
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/global/BaseTimeEntity.java
  src/main/java/com/spaceclub/invite/domain/Invite.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/invite/InviteTestFixture.java
  src/test/java/com/spaceclub/invite/service/InviteServiceTest.java
Labels: FEAT

#106 [ SKRB-200] feat: 초대 링크 생성시 관리자 권한 확인
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/invite/domain/Invite.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
Labels: FEAT

#109 [SKRB-293] docs: 남은 기능 api 명세
  src/docs/asciidoc/club-api.adoc
  src/docs/asciidoc/invite-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubNoticeCreateRequest.java
  src/main/java/com/spaceclub/club/controller/dto/ClubNoticeGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubUpdateRequest.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: documentation

#110 [SKRB-287] feat: 클럽 삭제 api 명세
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
Labels: FEAT

#111 feat: Controller Advice 추가
  src/main/java/com/spaceclub/global/ControllerAdvice.java
  src/main/java/com/spaceclub/global/config/JPAConfig.java
Labels: FEAT

#112 [SKRB-260] feat: 클럽 공지사항 CRU 구현, docs 변경
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubNoticeGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubNoticeUpdateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/domain/ClubNotice.java
  src/main/java/com/spaceclub/club/repository/ClubNoticeRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/vo/ClubNoticeUpdate.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/test/java/com/spaceclub/club/ClubNoticeTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
Labels: FEAT

#114 [SKRB-263] feat: 클럽 공지사항 삭제 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/vo/ClubNoticeDelete.java
Labels: FEAT

#115 [SKRB-264] docs: 클럽 일정 확인 api 명세 수정
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleResponse.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#116 [SKRB-264] feat: 클럽 일정 확인 api 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#117 [SKRB-265] feat: 클럽 수정하기 구현, docs 반영
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubUpdateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#118 [SKRB-296] feat: 3차 테스트 목표 컨트롤러 작성 및 api 문서화
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/BookmarkedEventRequest.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/vo/EventBookmarkInfo.java
  src/main/java/com/spaceclub/global/jwt/service/JwtService.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserBookmarkedEventGetResponse.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: documentation, FEAT

#120 [SKRB-298] feat: 북마크한 행사 조회하는 기능 구현
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserBookmarkedEventGetResponse.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#122 [SKRB-294] feat: 클럽 초대링크로 가입 전 확인 페이지 추가, docs 반영
  src/docs/asciidoc/invite-api.adoc
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/invite/controller/dto/ClubRequestToJoinResponse.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
Labels: FEAT

#124 [SKRB-299] feat: 사용자 정보 수정하는 기능 구현 (이름, 전화번호)
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserProfileUpdateRequest.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#125 [SKRB-311] feat: 클럽 가입의사 확인 시 토큰 검증 제거
  src/docs/asciidoc/invite-api.adoc
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
Labels: FEAT

#127 [SRKB-300] feat: 로그아웃 위한 admin key yml 파일에 등록 및 redirect url 임시 변경
  src/main/resources/global/application-oauth.yml
Labels: FEAT

#123 [SKRB-282] feat: 행사 신청 취소 기능 구현
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/event/controller/EventApplicationDeleteResponse.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#126 [SKRB-279] feat: 행사 검색 기능 구현
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/EventSearchGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#129 [SKRB-300] feat: 사용자 로그아웃 기능 구현
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/global/oauth/config/KakaoOauthInfoSender.java
  src/main/java/com/spaceclub/global/oauth/config/KakaoOauthProperties.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#131 [SKRB-312] feat: 클럽 삭제시 연관된 테이블 delete cascade 설정
  src/main/java/com/spaceclub/club/domain/Club.java
Labels: FEAT

#130 [SKRB-301] feat: 사용자 탈퇴 기능 구현
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/global/BaseTimeEntity.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#132 [SKRB-301] feat: 사용자 탈퇴 시 카카오 계정 연결 해제 기능 추가
  src/main/java/com/spaceclub/global/oauth/config/KakaoOauthInfoSender.java
  src/main/java/com/spaceclub/user/service/UserService.java
Labels: FEAT

#135 [SKRB-306] feat: s3 uploader 리팩토링 및 사용자 이미지 변경 기능 구현
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/global/S3ImageUploader.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/main/resources/global/application-s3.yml
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT, REFACTOR

#136 [ SKRB-303] refactor: 클럽 생성, 수정, 공지사항 수정, Controller Advice 안내 문구
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubCreateRequest.java
  src/main/java/com/spaceclub/club/controller/dto/ClubUpdateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/global/BaseTimeEntity.java
  src/main/java/com/spaceclub/global/ControllerAdvice.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: REFACTOR

#133 [SKRB-281] feat: 행사 삭제 기능 구현
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/domain/Form.java
  src/main/java/com/spaceclub/form/domain/FormOption.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#137 [SKRB-285] 카테고리 별 행사 생성 기능 구현
  build.gradle
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/club/controller/dto/ClubEventGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventCreateResponse.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ClubEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/PromotionEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/RecruitmentEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ShowEventCreateRequest.java
  src/main/java/com/spaceclub/event/domain/Category.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventCategory.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/domain/TicketInfo.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/domain/EventInfoTest.java
Labels: FEAT

#138 [SKRB-280] feat: 카테고리 별 행사 수정 기능 구현
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ClubEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/PromotionEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/RecruitmentEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ShowEventUpdateRequest.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#140 docs: PR 템플릿에 포스트맨 QA 여부 항목 추가
  .github/pull_request_template.md
Labels: documentation

#139 [SKRB-323] feat: 클럽 수정하기 api 메소드 PATCH로 수정
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#141 [SKRB-322] feat: 클럽 일정 조회시 필요한 내용 추가 전달
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleGetResponse.java
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/controller/dto/EventSearchGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
Labels: FEAT

#142 [SKRB-324] feat: 클럽 수정시 보내준 값에 대해서만 변경 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubUpdateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-parts.snippet
Labels: FEAT

#143 fix: 클럽 수정 시 NPE 해결
  src/main/java/com/spaceclub/club/controller/dto/ClubUpdateRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
Labels: bug

#145 [SKRB-316] feat: 폼 관련 변경사항 구현
  src/main/java/com/spaceclub/form/controller/dto/FormCreateRequest.java
  src/main/java/com/spaceclub/form/controller/dto/FormGetResponse.java
  src/main/java/com/spaceclub/form/domain/FormOption.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/vo/FormGet.java
  src/test/java/com/spaceclub/form/FormTestFixture.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#146 [SKRB-329] fix: 북마크 상태 변경 adoc event api에서 삭제
  src/docs/asciidoc/event-api.adoc
Labels: bug, documentation

#147 [SKRB-328] fix: bookmark 설정, 취소시 로직 수정
  src/main/java/com/spaceclub/user/domain/Bookmark.java
  src/main/java/com/spaceclub/user/repository/BookmarkRepository.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/user/repository/BookmarkRepositoryTest.java
Labels: bug, FEAT

#148 [SKRB-330] fix: 행사 신청 시 이미 신청한 행사라면 중복 신청 되지 않는 유효성 검사 추가
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
Labels: bug

#149 [SKRB-295] feat: 행사 신청 api 합치기 및 수정사항 반영
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/form-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventApplicationCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/EventApplicationDeleteResponse.java
  src/main/java/com/spaceclub/event/controller/dto/EventApplyRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/vo/EventApplicationCreateInfo.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#151 [SKRB-331] feat: 클럽 조회시 유저의 role 정보를 포함하도록 기능 추가
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#152 [SKRB-326] feat: 행사 상세 조회 카테고리별 조회 구현
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/ClubEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/PromotionEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/RecruitmentEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/ShowEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/controller/dto/ClubEventGetResponseTest.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/repository/EventRepositoryTest.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
  src/test/java/com/spaceclub/user/repository/BookmarkRepositoryTest.java
Labels: FEAT

#154 [SKRB-332] feat: 카테고리 별 전체 행사 조회 구현
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ClubEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/PromotionEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ShowEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ClubEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/PromotionEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ShowEventUpdateRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/domain/EventInfoTest.java
Labels: FEAT

#155 [SKRB-326] feat: 행사 상세 조회 api 구조 변경, docs 반영
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/ClubEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/PromotionEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/RecruitmentEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/detailGetResponse/ShowEventDetailGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: enhancement

#156 [SKRB-333] fix: 클럽 조회시 매니저가 아니면 조회할 수 없던 버그 수정
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
Labels: bug

#157 [SKRB-334] fix: 행사 공지사항 조회 시 매니저가 아니면 볼 수 없던 버그 수정
  src/main/java/com/spaceclub/club/service/ClubService.java
Labels: bug

#158 [SKRB-336] feat: 행사 신청, 행사의 신청된 폼 조회 api 관련 수정사항 반영
  src/docs/asciidoc/form-api.adoc
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationGetResponse.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/vo/FormApplicationGetInfo.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#160 [SKRB-339] feat: formOpenDate, formCloseDate 컬럼 명 변경
  src/main/java/com/spaceclub/event/controller/dto/EventGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ClubEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/PromotionEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/RecruitmentEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ShowEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ClubEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/PromotionEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/RecruitmentEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ShowEventUpdateRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/FormInfo.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/domain/FormInfoTest.java
Labels: FEAT

#166 [SKRB-341] fix: 북마크 변경 오류 및 프로필 사진 변경 오류 수정
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/UserService.java
Labels: bug

#161 [SKRB-338] feat: 행사 상세 조회 시 필요한 정보 추가
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#162 [SKRB-169] feat: interceptor에서 access token 및 refresh token 인증기능 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/global/config/SecurityServiceConfig.java
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/spaceclub/global/interceptor/JwtAuthorizationInterceptor.java
  src/main/java/com/spaceclub/global/jwt/Jwt.java
  src/main/java/com/spaceclub/global/jwt/JwtConfig.java
  src/main/java/com/spaceclub/global/jwt/JwtProperties.java
  src/main/java/com/spaceclub/global/jwt/service/JwtManager.java
  src/main/java/com/spaceclub/global/jwt/service/JwtService.java
  src/main/java/com/spaceclub/global/jwt/vo/JwtUser.java
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/resources/global/application-oauth.yml
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#163 [SRKB-170] feat: 로그인 및 회원가입 시 refresh token 발급 기능 구현
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/global/jwt/service/JwtManager.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserLoginResponse.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#164 [SKRB-340] feat: argument resolver로 인증 관련 controller 공통 관심사 분리
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/global/Authenticated.java
  src/main/java/com/spaceclub/global/UserArgumentResolver.java
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/global/jwt/service/JwtManager.java
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT, REFACTOR

#165 [SKRB-337] feat: 클럽 조회시 클럽 유저 권한 조회 api 분리
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubUserRoleResponse.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#170 [SKRB-351] fix: 이벤트 상세 조회시 클럽 일정만 종료 날짜, 시간 존재하게끔 수정
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: bug

#171 [SKRB-352] fix: 클럽 초대 링크 만료시 자동 갱신 구현
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/invite/domain/Invite.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
Labels: bug

#167 [SKRB-314] feat: 담당 api 권한 처리 구현
  src/docs/asciidoc/club-api.adoc
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleGetResponse.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/vo/ClubUserUpdate.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
  src/test/java/com/spaceclub/user/service/UserServiceTest.java
Labels: FEAT

#168 [SKRB-243] feat: 클럽 멤버 조회하기 정렬 기준 추가
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/MemberGetResponse.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/domain/ClubUserRole.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/dto/MemberGetResponseTest.java
Labels: FEAT

#169 [SKRB-346] feat: 행사 신청 상태 변경 기능 구현
  src/docs/asciidoc/form-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/MemberGetResponse.java
  src/main/java/com/spaceclub/club/domain/ClubUserRole.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationGetResponse.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationStatusUpdateRequest.java
  src/main/java/com/spaceclub/form/domain/FormOptionUser.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: FEAT

#172 [SRKB-361] fix: profile image 조회시 s3 주소 prefix로 붙혀 반환하도록 변경
  src/main/java/com/spaceclub/user/domain/User.java
Labels: bug

#174 [SKRB-373] fix: 행사 검색 api의 Authorization 헤더 제거
  src/docs/asciidoc/event-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: bug

#178 [SKRB-349] feat: Exception enum 추출, docs 작성
  src/docs/asciidoc/exception-api.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/global/ExceptionCode.java
  src/main/java/com/spaceclub/global/interceptor/JwtAuthorizationInterceptor.java
  src/main/java/com/spaceclub/global/jwt/service/JwtManager.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/main/java/com/spaceclub/user/service/UserService.java
Labels: FEAT

#179 [SKRB-374] feat: 클럽 로고 이미지 저장시 URL prefix 제거
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubService.java
Labels: FEAT

#181 [hotfix] docs: 예외 문구 통일 docs 반영
  src/docs/asciidoc/exception-api.adoc
Labels: documentation, enhancement

#176 [SRKB-377] feat: jwtManager 불필요한 메서드 제거 및 패키지 이동
  src/main/java/com/spaceclub/global/UserArgumentResolver.java
  src/main/java/com/spaceclub/global/interceptor/JwtAuthorizationInterceptor.java
  src/main/java/com/spaceclub/global/jwt/JwtManager.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: REFACTOR

#182 [hotfix] docs: request header에 optional 컬럼 추가
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-headers.snippet
Labels: documentation, FEAT

#183 [SKRB-382] feat: Authorization Header 필수 여부 docs 기록
  src/docs/asciidoc/event-api.adoc
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#177 [SKRB-362] feat: role이 멤버일 경우, 사용자 클럽 탈퇴 기능 구현
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#180 [SKRB-348] Logback을 통한 로그 환경 설정
  src/main/java/com/spaceclub/global/log/HttpAspect.java
  src/main/java/com/spaceclub/global/log/HttpLogResponse.java
  src/main/java/com/spaceclub/global/log/PointCuts.java
  src/main/java/com/spaceclub/global/log/PrepareStateInspector.java
  src/main/java/com/spaceclub/global/log/RequestWrapper.java
  src/main/java/com/spaceclub/global/log/SqlLogConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: FEAT

#175 [SRKB-376] feat: 인증 및 인가 interceptor 분리
  src/main/java/com/spaceclub/global/UserArgumentResolver.java
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/global/interceptor/AuthenticationInterceptor.java
  src/main/java/com/spaceclub/global/jwt/vo/JwtUser.java
Labels: FEAT

#185 [HOTFIX] fix: ec2 파일 접근 권한 문제 해결 및 acess token 시간 연장
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/resources/global/application-oauth.yml
  src/main/resources/logback-spring.xml
Labels: bug

#184 [SKRB-375] feat: 클럽 수정 시 배경 이미지 설정 구현
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/global/S3ImageUploader.java
  src/main/resources/global/application-s3.yml
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#187 [SKRB-384] fix: 폼 신청 상태 변경 api의 request에 formUserId 추가
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationStatusUpdateRequest.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/vo/FormApplicationUpdateInfo.java
  src/main/java/com/spaceclub/global/ExceptionCode.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
Labels: bug

#188 [SKRB-375] feat: 클럽 엔티티의 로고, 배경이미지 이름 변경, prefix getter에 삽입
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/user/controller/dto/UserClubGetResponse.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
  src/test/java/com/spaceclub/user/repository/BookmarkRepositoryTest.java
Labels: FEAT

#190 refactor: event, form 도메인 리펙토링
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/exception-api.adoc
  src/docs/asciidoc/form-api.adoc
  src/main/java/com/spaceclub/club/controller/EventCreateConverter.java
  src/main/java/com/spaceclub/club/controller/EventUpdateConverter.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/ParticipationController.java
  src/main/java/com/spaceclub/event/controller/dto/EventApplicationDeleteResponse.java
  src/main/java/com/spaceclub/event/controller/dto/EventParticipationCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/EventParticipationDeleteResponse.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ClubEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/PromotionEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/RecruitmentEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ShowEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ClubEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/PromotionEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/RecruitmentEventUpdateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ShowEventUpdateRequest.java
  src/main/java/com/spaceclub/event/domain/BankInfo.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/event/domain/ParticipationStatus.java
  src/main/java/com/spaceclub/event/domain/TicketInfo.java
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/EventValidator.java
  src/main/java/com/spaceclub/event/service/ParticipationService.java
  src/main/java/com/spaceclub/event/service/vo/EventCreateInfo.java
  src/main/java/com/spaceclub/event/service/vo/EventParticipationCreateInfo.java
  src/main/java/com/spaceclub/form/controller/FormController.java
  src/main/java/com/spaceclub/form/controller/SubmitController.java
  src/main/java/com/spaceclub/form/controller/dto/FormApplicationStatusUpdateRequest.java
  src/main/java/com/spaceclub/form/controller/dto/FormGetResponse.java
  src/main/java/com/spaceclub/form/controller/dto/FormSubmitGetResponse.java
  src/main/java/com/spaceclub/form/controller/dto/FormSubmitUpdateRequest.java
  src/main/java/com/spaceclub/form/domain/FormOptionUser.java
  src/main/java/com/spaceclub/form/service/ClubUserValidator.java
  src/main/java/com/spaceclub/form/service/FormOptionService.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/SubmitService.java
  src/main/java/com/spaceclub/form/service/vo/FormApplicationUpdateInfo.java
  src/main/java/com/spaceclub/form/service/vo/FormCreateInfo.java
  src/main/java/com/spaceclub/form/service/vo/FormGetInfo.java
  src/main/java/com/spaceclub/form/service/vo/FormSubmitGetInfo.java
  src/main/java/com/spaceclub/form/service/vo/FormSubmitUpdateInfo.java
  src/main/java/com/spaceclub/global/ExceptionCode.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/controller/ParticipationControllerTest.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
  src/test/java/com/spaceclub/form/FormTestFixture.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
  src/test/java/com/spaceclub/form/controller/SubmitControllerTest.java
Labels: REFACTOR

#191 refactor : 유저 도메인 리팩토링
  src/docs/asciidoc/user-api.adoc
  src/main/java/com/spaceclub/club/service/ClubMemberManagerService.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/vo/MemberGetInfo.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/ParticipationService.java
  src/main/java/com/spaceclub/user/controller/BookmarkController.java
  src/main/java/com/spaceclub/user/controller/ContentController.java
  src/main/java/com/spaceclub/user/controller/LoginController.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserLoginResponse.java
  src/main/java/com/spaceclub/user/domain/Bookmark.java
  src/main/java/com/spaceclub/user/repository/BookmarkRepository.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/main/java/com/spaceclub/user/service/BookmarkCommandProvider.java
  src/main/java/com/spaceclub/user/service/BookmarkService.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/main/java/com/spaceclub/user/service/vo/BookmarkCommand.java
  src/main/java/com/spaceclub/user/service/vo/RequiredProfile.java
  src/main/java/com/spaceclub/user/service/vo/UserLoginInfo.java
  src/main/java/com/spaceclub/user/service/vo/UserProfile.java
  src/main/java/com/spaceclub/user/service/vo/UserRequiredInfo.java
  src/test/java/com/spaceclub/user/controller/BookmarkControllerTest.java
  src/test/java/com/spaceclub/user/controller/ContentControllerTest.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
  src/test/java/com/spaceclub/user/repository/BookmarkRepositoryTest.java
  src/test/java/com/spaceclub/user/service/UserServiceTest.java
Labels: REFACTOR

#192 refactor: 타 도메인 서비스 메서드 의존성 분리
  src/main/java/com/spaceclub/event/service/ParticipationService.java
  src/main/java/com/spaceclub/form/service/FormOptionProvider.java
  src/main/java/com/spaceclub/form/service/FormOptionService.java
  src/main/java/com/spaceclub/form/service/vo/FormUserInfo.java
Labels: REFACTOR

#194 refactor: club 도메인 - 외부 서비스 의존성 인터페이스로 변경
  src/main/java/com/spaceclub/club/controller/ClubEventController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubEventGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubEventService.java
  src/main/java/com/spaceclub/event/service/EventProvider.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/vo/EventGetInfo.java
  src/main/java/com/spaceclub/event/service/vo/SchedulesGetInfo.java
  src/main/java/com/spaceclub/invite/service/InviteJoinService.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/club/controller/dto/ClubEventGetResponseTest.java
  src/test/java/com/spaceclub/invite/service/InviteJoinServiceTest.java~develop
  src/test/java/com/spaceclub/invite/service/InviteJoinServiceTest.java~refactor: club 도메인
Labels: REFACTOR

#196 fix: rebase하면서 생긴 파일 제거
  src/test/java/com/spaceclub/invite/service/InviteJoinServiceTest.java~develop
  src/test/java/com/spaceclub/invite/service/InviteJoinServiceTest.java~refactor: club 도메인
Labels: bug

#197 fix: 클럽 멤버 조회시 신청자의 정보로만 도배되던 버그 수정
  src/main/java/com/spaceclub/club/service/ClubMemberManagerService.java
Labels: bug

#199 fix: 멤버 조회 권한 클럽 멤버로 수정
  src/main/java/com/spaceclub/club/service/ClubMemberManagerService.java
Labels: bug

#202 [SKRB-389] feat: rest docs 리팩토링 및 불필요한 api 삭제
  src/docs/asciidoc/user-api.adoc
  src/docs/asciidoc/user/bookmark-api.adoc
  src/docs/asciidoc/user/content-api.adoc
  src/docs/asciidoc/user/login-api.adoc
  src/docs/asciidoc/user/profile-api.adoc
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/test/java/com/spaceclub/user/controller/BookmarkControllerTest.java
  src/test/java/com/spaceclub/user/controller/ContentControllerTest.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT, REFACTOR

#201 [SKRB-353] feat: 이벤트 카테고리 중 클럽 일정인 경우에만 클럽 멤버(매니저) 검증 하게끔 수정
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/service/ClubUserValidator.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: bug

#200 [SKRB-386] fix: 행사 수정 api 수정 및 Club, User관련 이미지 null 처리
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubUserValidator.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/SubmitService.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/domain/EventInfoTest.java
Labels: bug

#204 [HOTFIX] fix: rest docs 수정
  src/docs/asciidoc/user/bookmark-api.adoc
  src/docs/asciidoc/user/content-api.adoc
  src/docs/asciidoc/user/login-api.adoc
  src/docs/asciidoc/user/profile-api.adoc
Labels: bug

#205 [HOTIFX] fix: rest docs snippet 경로 수정
  src/docs/asciidoc/user/bookmark-api.adoc
  src/docs/asciidoc/user/content-api.adoc
  src/docs/asciidoc/user/login-api.adoc
  src/docs/asciidoc/user/profile-api.adoc
Labels: bug

#206 [HOTFIX] fix: rest docs 수정
  src/docs/asciidoc/user/bookmark-api.adoc
  src/docs/asciidoc/user/content-api.adoc
  src/docs/asciidoc/user/login-api.adoc
  src/docs/asciidoc/user/profile-api.adoc
Labels: bug

#203 [SKRB-387] feat: 예외 메세지 도메인 별 분리
  src/main/java/com/spaceclub/club/ClubExceptionMessage.java
  src/main/java/com/spaceclub/club/controller/EventUpdateConverter.java
  src/main/java/com/spaceclub/club/service/ClubEventService.java
  src/main/java/com/spaceclub/club/service/ClubMemberManagerService.java
  src/main/java/com/spaceclub/club/service/ClubNoticeService.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/club/service/ClubUserValidator.java
  src/main/java/com/spaceclub/event/EventExceptionMessage.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/EventValidator.java
  src/main/java/com/spaceclub/event/service/ParticipationService.java
  src/main/java/com/spaceclub/form/FormExceptionMessage.java
  src/main/java/com/spaceclub/form/service/FormOptionService.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/SubmitService.java
  src/main/java/com/spaceclub/global/ExceptionCode.java
  src/main/java/com/spaceclub/global/exception/ControllerAdvice.java
  src/main/java/com/spaceclub/global/exception/ExceptionMessageInterface.java
  src/main/java/com/spaceclub/global/exception/GlobalExceptionCode.java
  src/main/java/com/spaceclub/global/jwt/JwtManager.java
  src/main/java/com/spaceclub/invite/InviteExceptionMessage.java
  src/main/java/com/spaceclub/invite/service/InviteJoinService.java
  src/main/java/com/spaceclub/user/UserExceptionMessage.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/main/java/com/spaceclub/user/service/BookmarkService.java
  src/main/java/com/spaceclub/user/service/UserService.java
Labels: FEAT, REFACTOR

#209 [SKRB-390] ] fix: 폼 관리모드 설정 안할 시 조회 안되는 오류 수정
  src/main/java/com/spaceclub/event/service/EventValidator.java
  src/main/java/com/spaceclub/form/service/FormService.java
  src/main/java/com/spaceclub/form/service/SubmitService.java
Labels: bug

#208 [SKRB-338] feat: 행사 상세 조회시 response 분류
  src/main/java/com/spaceclub/club/service/ClubUserValidator.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#210 [SRKB-388] feat: s3 및 oauth 설정 모두 설정 파일로 분리 및 이미지 값 null일 경우 null 반환 하도록 문제 해결
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/global/config/PropertiesConfig.java
  src/main/java/com/spaceclub/global/config/oauth/KakaoOauthInfoSender.java
  src/main/java/com/spaceclub/global/config/oauth/KakaoOauthProperties.java
  src/main/java/com/spaceclub/global/config/oauth/KakaoRequestUrlProperties.java
  src/main/java/com/spaceclub/global/config/oauth/vo/KakaoTokenInfo.java
  src/main/java/com/spaceclub/global/config/oauth/vo/KakaoUserInfo.java
  src/main/java/com/spaceclub/global/config/s3/S3Config.java
  src/main/java/com/spaceclub/global/config/s3/S3ImageUploader.java
  src/main/java/com/spaceclub/global/config/s3/properties/S3BucketUrl.java
  src/main/java/com/spaceclub/global/config/s3/properties/S3FolderProperties.java
  src/main/java/com/spaceclub/global/config/s3/properties/S3IamProperties.java
  src/main/java/com/spaceclub/global/oauth/config/KakaoOauthProperties.java
  src/main/java/com/spaceclub/global/oauth/config/KakaoPropertiesConfig.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/main/java/com/spaceclub/user/service/vo/UserProfile.java
  src/main/resources/develop/application-develop.yml
  src/main/resources/global/application-oauth.yml
  src/main/resources/global/application-s3.yml
Labels: FEAT, REFACTOR

#211 [SKRB-383] chore: 로그아웃 기능 제거
  src/docs/asciidoc/user/login-api.adoc
  src/main/java/com/spaceclub/user/controller/LoginController.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
Labels: documentation

#212 [SKRB-393] feat: controller advice 설정 및 토큰 상황 별 예외 생성
  src/main/java/com/spaceclub/global/exception/AccessTokenException.java
  src/main/java/com/spaceclub/global/exception/ControllerAdvice.java
  src/main/java/com/spaceclub/global/exception/GlobalExceptionCode.java
  src/main/java/com/spaceclub/global/exception/RefreshTokenException.java
  src/main/java/com/spaceclub/global/exception/TokenException.java
  src/main/java/com/spaceclub/global/exception/advice/ControllerAdvice.java
  src/main/java/com/spaceclub/global/exception/advice/ErrorResponse.java
  src/main/java/com/spaceclub/global/interceptor/JwtAuthorizationInterceptor.java
  src/main/java/com/spaceclub/global/jwt/Jwt.java
  src/main/java/com/spaceclub/global/jwt/JwtManager.java
  src/main/java/com/spaceclub/user/controller/BookmarkController.java
Labels: FEAT

#213 [SKRB-338] feat: 공연 상세 조회시 필요없는 필드 제거
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#214 [SKRB-401] feat: 행사 상세 조회시 clubId 추가
  src/main/java/com/spaceclub/event/controller/ParticipationController.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#215 [SKRB-391] feat: 행사 신청이 취소 완료된 경우 재신청 가능하도록 구현
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/event/service/ParticipationService.java
  src/main/java/com/spaceclub/form/FormExceptionMessage.java
  src/main/java/com/spaceclub/form/domain/FormOption.java
  src/main/java/com/spaceclub/form/repository/FormOptionUserRepository.java
  src/main/java/com/spaceclub/form/service/FormOptionProvider.java
  src/main/java/com/spaceclub/form/service/FormOptionService.java
Labels: FEAT

#216 [SKRB-397] feat: 인증 및 인가 인터셉터 분리 및 경로 재설정
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/global/interceptor/AuthenticationInterceptor.java
  src/main/java/com/spaceclub/global/interceptor/AuthorizationInterceptor.java
  src/main/java/com/spaceclub/global/interceptor/JwtAuthenticationProvider.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/club/controller/ClubNoticeControllerTest.java
  src/test/java/com/spaceclub/club/controller/ClubUserControllerTest.java
  src/test/java/com/spaceclub/club/controller/dto/MemberGetInfoTest.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/controller/ParticipationControllerTest.java
  src/test/java/com/spaceclub/form/controller/FormControllerTest.java
  src/test/java/com/spaceclub/form/controller/SubmitControllerTest.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
  src/test/java/com/spaceclub/invite/controller/InviteJoinControllerTest.java
  src/test/java/com/spaceclub/user/controller/BookmarkControllerTest.java
  src/test/java/com/spaceclub/user/controller/ContentControllerTest.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
  src/test/java/com/spaceclub/user/domain/UserTest.java
Labels: enhancement, FEAT, REFACTOR

#218 [SKRB-405] feat: Bookmark 컨트롤러에서 EventService 의존성 인터페이스로 치환
  src/main/java/com/spaceclub/event/service/EventProvider.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/user/controller/BookmarkController.java
  src/main/java/com/spaceclub/user/controller/dto/UserBookmarkedEventGetResponse.java
  src/test/java/com/spaceclub/user/controller/BookmarkControllerTest.java
Labels: FEAT, REFACTOR

#224 [SKRB-402] feat: 행사 리스트 조회 관련 api에 행사 종료 여부 추가
  src/main/java/com/spaceclub/club/controller/dto/ClubEventGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/EventOverviewGetResponse.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#225 [SKRB-407] feat: 클럽 일정 조회 api 삭제, 행사 생성, 수정 api의 request에서 managerName 삭제
  src/docs/asciidoc/club-api.adoc
  src/main/java/com/spaceclub/club/controller/ClubEventController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubScheduleGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubEventService.java
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ClubEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ClubEventUpdateRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventProvider.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/vo/SchedulesGetInfo.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#226 [SKRB-412] feat: 행사 생성 api 담당자 저장 로직 구현 및 클럽 행사 조회 api의 ResponseBody에 managerInfo 추가
  src/main/java/com/spaceclub/club/controller/ClubEventController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubEventGetResponse.java
  src/main/java/com/spaceclub/club/controller/dto/ClubEventOverviewGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubEventService.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/service/EventProvider.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/vo/ClubEventOverviewGetInfo.java
  src/main/java/com/spaceclub/event/service/vo/UserBookmarkedEventGetInfo.java
  src/main/java/com/spaceclub/user/controller/BookmarkController.java
  src/main/java/com/spaceclub/user/controller/dto/UserBookmarkedEventGetResponse.java
  src/main/java/com/spaceclub/user/service/UserProvider.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/event/repository/EventRepositoryTest.java
  src/test/java/com/spaceclub/user/controller/BookmarkControllerTest.java
Labels: FEAT

#229 [SKRB-403] feat: 모든 행사 조회 api에 clubCoverImageUrl 추가 및 isEnded 쿼리 파라미터 추가
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventOverviewGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/form/FormExceptionMessage.java
  src/main/java/com/spaceclub/form/domain/FormAnswer.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#220 [SKRB-405] feat: 회원 탈퇴 기능 구현 - 속해 있는 클럽이 없을 경우 유저의 상태를 inactive로 변경하는 기능 구현
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/club/repository/ClubUserRepository.java
  src/main/java/com/spaceclub/club/service/ClubProvider.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/global/exception/TokenException.java
  src/main/java/com/spaceclub/user/UserExceptionMessage.java
  src/main/java/com/spaceclub/user/controller/LoginController.java
  src/main/java/com/spaceclub/user/domain/Status.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
  src/test/java/com/spaceclub/user/domain/UserTest.java
Labels: FEAT

#221 [SKRB-395] feat: 유저의 상태가 INACTIVE일 경우 로그인 시 탈퇴 해제 기능 구현
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/test/java/com/spaceclub/user/UserTestFixture.java
  src/test/java/com/spaceclub/user/service/AccountServiceTest.java
Labels: FEAT

#231 [HOTFIX] fix: username와 phonenumber 저장 안되는 기능 수정
  src/main/java/com/spaceclub/user/controller/LoginController.java
  src/main/java/com/spaceclub/user/controller/dto/UserRequiredInfoRequest.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
Labels: bug

#232 [HOTFIX] docs: global exception message docs 최신화
  src/docs/asciidoc/exception-api.adoc
Labels: documentation

#233 [HOTFIX] feat: cors 설정 시 http 전체 메서드 허용 및 authorization시 null 검증 추가
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/global/interceptor/AuthorizationInterceptor.java
Labels: bug

#234 [HOTFIX] feat: 유저 필수정보 업데이트 시 토큰 재발급 기능 구현
  src/docs/asciidoc/user/profile-api.adoc
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#219 [SKRB-400] feat: 초대링크, 만료여부 조회 api 구현
  src/docs/asciidoc/invite-api.adoc
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/invite/controller/dto/InviteGetResponse.java
  src/main/java/com/spaceclub/invite/repository/InviteRepository.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
  src/main/java/com/spaceclub/invite/service/vo/InviteGetInfo.java
  src/test/java/com/spaceclub/invite/controller/InviteControllerTest.java
Labels: FEAT

#228 [SKRB-396] feat: 회원 탈퇴 후 유예기간 3일이 지나면 비동기 스케줄링을 통해 soft delete 기능 구현
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/global/config/AsyncConfig.java
  src/main/java/com/spaceclub/global/config/CustomAsyncExceptionHandler.java
  src/main/java/com/spaceclub/global/config/EncryptionConfig.java
  src/main/java/com/spaceclub/global/config/WebConfig.java
  src/main/java/com/spaceclub/user/UserExceptionMessage.java
  src/main/java/com/spaceclub/user/controller/LoginController.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/repository/UserRepository.java
  src/main/java/com/spaceclub/user/service/AccountDeleteScheduler.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/test/java/com/spaceclub/user/UserTestFixture.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
  src/test/java/com/spaceclub/user/domain/UserTest.java
  src/test/java/com/spaceclub/user/repository/UserRepositoryTest.java
  src/test/java/com/spaceclub/user/service/AccountServiceTest.java
Labels: documentation, enhancement, FEAT

#230 [SKRB-413] feat: 행사 검색 ResponseDto 분리 및 QueryParameter를 사용하고 있는 api의 optional 설정
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventSearchOverviewGetResponse.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/form/controller/SubmitControllerTest.java
  src/test/java/com/spaceclub/user/controller/BookmarkControllerTest.java
  src/test/java/com/spaceclub/user/controller/ContentControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
Labels: FEAT

#235 [SKRB-414] fix: 클럽 행사 개설 시 posterImage 선택값 처리
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/event/EventExceptionMessage.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: bug

#237 [HOTFIX] fix: deletedAt 컬럼 NPE 해결
  src/main/java/com/spaceclub/user/domain/User.java
Labels: bug

#238 [HOTFIX] fix: deletedAt 컬럼 NPE 해결
  src/main/java/com/spaceclub/user/domain/User.java
Labels: bug

#236 [SKRB-415] feat: 모든 행사 조회, 클럽 행사 조회 시 size default값 설정
  src/main/java/com/spaceclub/club/controller/ClubEventController.java
  src/main/java/com/spaceclub/event/controller/EventController.java
Labels: FEAT

#239 [SKRB-420] fix: 초대링크가 조회할 때 없을 경우 null 반환
  src/main/java/com/spaceclub/invite/controller/InviteController.java
  src/main/java/com/spaceclub/invite/service/InviteService.java
Labels: FEAT

#246 [SKRB-409] feat: 행사 상세 조회
  src/main/java/com/spaceclub/club/controller/EventCreateConverter.java
  src/main/java/com/spaceclub/event/controller/dto/EventDetailGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#241 [SKRB-418] feat: 행사의 신청된 폼 조회 api에 신청 날짜 및 시각 추가
  src/main/java/com/spaceclub/event/controller/ParticipationController.java
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/form/controller/SubmitController.java
  src/main/java/com/spaceclub/form/controller/dto/FormSubmitGetResponse.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/form/controller/SubmitControllerTest.java
Labels: FEAT

#243 [SKRB-427] fix: 행사 생성, 수정 api의 ResponseDto Integer로 형 변경
  src/main/java/com/spaceclub/event/controller/dto/createRequest/ClubEventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/updateRequest/ClubEventUpdateRequest.java
Labels: bug

#245 [SKRB-426] refactor: 행사, 폼 관련 adoc 파일 분리
  src/docs/asciidoc/club-api.adoc
  src/docs/asciidoc/event-api.adoc
  src/docs/asciidoc/event/event-api.adoc
  src/docs/asciidoc/event/participation-api.adoc
  src/docs/asciidoc/exception-api.adoc
  src/docs/asciidoc/form-api.adoc
  src/docs/asciidoc/form/form-api.adoc
  src/docs/asciidoc/form/submit-api.adoc
Labels: REFACTOR

#248 fix: adoc 경로 snippet으로 변경
  src/docs/asciidoc/event/event-api.adoc
  src/docs/asciidoc/event/participation-api.adoc
  src/docs/asciidoc/form/form-api.adoc
  src/docs/asciidoc/form/submit-api.adoc
Labels: bug
