Repository Space-Club/Backend, pull requests merged in 2023-10, with the labels that each got.

#8 [SKRB-148] feat: 행사 생성 API 틀 구현
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/CreateEventRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
Labels: FEAT

#11 [SKRB-141] feat: 행사 생성 RequestDto 구현
  src/main/java/com/spaceclub/event/controller/dto/CreateEventRequest.java
  src/main/java/com/spaceclub/event/domain/BankInfo.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/domain/FormInfo.java
  src/main/java/com/spaceclub/event/domain/TicketInfo.java
Labels: FEAT

#9 [SKRB-151] feat: 테스트 컨벤션에 따른 DisplayNameGenerator 생성
  src/test/java/com/spaceclub/SpaceClubBackendApplicationTests.java
  src/test/java/com/spaceclub/SpaceClubCustomDisplayNameGenerator.java
Labels: FEAT

#10 [SKRB-146] feat: user 도메인 생성 및 검증 로직 테스트
  src/main/java/com/spaceclub/user/domain/Email.java
  src/main/java/com/spaceclub/user/domain/PhoneNumber.java
  src/main/java/com/spaceclub/user/domain/Provider.java
  src/main/java/com/spaceclub/user/domain/RequiredInfo.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/test/java/com/spaceclub/user/domain/EmailTest.java
  src/test/java/com/spaceclub/user/domain/PhoneNumberTest.java
  src/test/java/com/spaceclub/user/domain/RequiredInfoTest.java
Labels: FEAT

#12 [SKRB-152] feat: 암호화를 통한 develop 환경 서브모듈로 부터 제거
  build.gradle
  scripts/deploy.sh
  scripts/properties.sh
  src/main/java/com/spaceclub/SpaceClubBackendApplication.java
  src/main/java/com/spaceclub/global/config/PropertiesConfig.java
  src/main/resources/develop/application-develop.yml
  src/test/java/com/spaceclub/global/utils/EncryptionTest.java
Labels: FEAT

#13 [ SKRB-143] feat: 클럽 엔티티, 서비스 및 리포지토리 생성
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/repository/ClubRepository.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#15 [SKRB-154] test: Club 엔티티 테스트 코드 작성
  src/main/java/com/spaceclub/club/domain/Club.java
  src/test/java/com/spaceclub/club/domain/ClubTest.java
Labels: enhancement

#14 [ SKRB-159] feat: Club 생성 관련 세부 기능 구현, dto 구체화
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/CreateClubRequest.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#18 [SKRB-183] fix: jasypt 관련 PropertiesConfig 설정 변경
  src/main/java/com/spaceclub/global/config/PropertiesConfig.java
Labels: bug

#16 [SKRB-156] feat: 클럽 조회, 그와 관련된 보조 테이블 생성과 연관관계 설정
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubCreateRequest.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/domain/ClubNotice.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#21 [SKRB-184] refactor: DTO 이름 변경 및 SpaceClubCustomDisplayNameGenerator 수정
  src/main/java/com/spaceclub/global/dto/PageResponse.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserEventGetResponse.java
  src/test/java/com/spaceclub/SpaceClubCustomDisplayNameGenerator.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/domain/ClubTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
  src/test/java/com/spaceclub/user/domain/EmailTest.java
  src/test/java/com/spaceclub/user/domain/PhoneNumberTest.java
  src/test/java/com/spaceclub/user/domain/RequiredInfoTest.java
Labels: REFACTOR

#20 [SKRB-158] feat: S3를 이용한 행사 생성 API 구현
  build.gradle
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/CreateEventRequest.java
  src/main/java/com/spaceclub/global/S3ImageUploader.java
  src/main/java/com/spaceclub/global/config/S3Config.java
  src/main/resources/develop/application-develop.yml
  src/main/resources/local/application-local.yml
Labels: FEAT

#22 [SKRB-157] feat: 클럽 삭제 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
Labels: FEAT

#33 [SKRB-187] feat: index.adoc 설정 변경
  build.gradle
  src/docs/asciidoc/index.adoc
Labels: FEAT

#34 [SKRB-187] feat: spring rest docs 경로 설정 및 index.adoc 생성
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
Labels: FEAT

#24 [SKRB-185] feat: Event 테이블에 Club 연관관계 설정
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventCreateRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#27 [SKRB-160] feat: 전체 행사 조회 API 구현
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventCreateRequest.java
  src/main/java/com/spaceclub/event/controller/dto/EventGetResponse.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#36 [SKRB-186] test: 행사 생성, 모든 행사 조회 controller 테스트
  .gitignore
  src/docs/asciidoc/index.adoc
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#37 [SKRB-189] chore: PR 템플릿 수정
  .github/pull_request_template.md
Labels: documentation

#30 [SKRB-175] test: 클럽 조회, 삭제 서비스 테스트 작성
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/domain/ClubNotice.java
  src/main/java/com/spaceclub/club/domain/ClubUser.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
Labels: FEAT

#44 [ SKRB-150] feat: 사용자의 간단한 행사 신청, 테스트 코드 작성
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventApplyRequest.java
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/event/repository/EventUserRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
Labels: FEAT

#50 feat: allowedOrigins 통합
  src/main/java/com/spaceclub/global/config/WebConfig.java
Labels: bug

#53 [SKRB-211] feat: 클럽 행사 조회 api 틀 구현
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubEventGetResponse.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/domain/Category.java
  src/main/java/com/spaceclub/event/domain/Event.java
Labels: FEAT

#54 [SKRB-217] feat: 클럽 생성 요청시 이미지 업로드 multipart 적용
  src/main/java/com/spaceclub/club/controller/ClubController.java
  src/main/java/com/spaceclub/club/controller/dto/ClubCreateRequest.java
  src/main/java/com/spaceclub/club/controller/dto/ClubGetResponse.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/event/controller/dto/EventGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/global/S3ImageUploader.java
  src/main/resources/develop/application-develop.yml
  src/main/resources/local/application-local.yml
  src/test/java/com/spaceclub/club/ClubTestFixture.java
  src/test/java/com/spaceclub/club/controller/ClubControllerTest.java
  src/test/java/com/spaceclub/club/service/ClubServiceTest.java
  src/test/java/com/spaceclub/event/repository/EventUserRepositoryTest.java
Labels: FEAT
