Repository Space-Club/Backend, pull requests merged in 2023-12, with the labels that each got.

#266 feat, fix: s3 url관련 null 처리 및 행사 배너 조회 api에서 클럽 일정 행사 제외하도록 구현
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventBannerResponse.java
  src/main/java/com/spaceclub/event/controller/dto/EventOverviewGetResponse.java
  src/main/java/com/spaceclub/event/controller/dto/EventSearchOverviewGetResponse.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/main/java/com/spaceclub/event/service/vo/ClubEventOverviewGetInfo.java
  src/main/java/com/spaceclub/invite/controller/dto/ClubRequestToJoinResponse.java
Labels: FEAT

#267 feat: 유저의 신청된 행사 조회, 제출된 폼 조회 api에 ticketCount 추가
  src/main/java/com/spaceclub/event/domain/EventUser.java
  src/main/java/com/spaceclub/event/service/UserEventProvider.java
  src/main/java/com/spaceclub/event/service/UserEventService.java
  src/main/java/com/spaceclub/event/service/vo/EventPageInfo.java
  src/main/java/com/spaceclub/form/controller/dto/FormSubmitGetResponse.java
  src/main/java/com/spaceclub/user/controller/ContentController.java
  src/main/java/com/spaceclub/user/controller/dto/UserEventGetResponse.java
  src/test/java/com/spaceclub/event/EventTestFixture.java
  src/test/java/com/spaceclub/form/controller/SubmitControllerTest.java
  src/test/java/com/spaceclub/user/controller/ContentControllerTest.java
Labels: FEAT

#268 [SKRB-438] fix: 클럽 이름 중복 방지
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/club/ClubExceptionMessage.java
  src/main/java/com/spaceclub/club/domain/Club.java
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/global/exception/advice/ControllerAdvice.java
  src/test/java/com/spaceclub/club/ClubTestFixture.java
Labels: bug

#271 feat: 모든 행사 정렬 추가 및 행사 최소 정원 0으로 변경
  src/main/java/com/spaceclub/event/controller/EventController.java
  src/main/java/com/spaceclub/event/controller/dto/EventOverviewGetResponse.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/TicketInfo.java
  src/main/java/com/spaceclub/event/service/EventService.java
  src/test/java/com/spaceclub/event/controller/EventControllerTest.java
  src/test/java/com/spaceclub/event/domain/TicketInfoTest.java
Labels: FEAT

#276 fix: 행사 수정 시 지원자 수 초기화 되는 문제 해결
  src/main/java/com/spaceclub/event/controller/dto/EventUpdateRequest.java
  src/main/java/com/spaceclub/event/domain/Event.java
  src/main/java/com/spaceclub/event/domain/EventInfo.java
  src/main/java/com/spaceclub/event/service/EventService.java
Labels: bug

#277 feat: 행사 배너 api 신청 가능한 행사만 나오도록 수정
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventService.java
Labels: FEAT

#272 [SKRB-432] feat: 이메일 수정 기능 추가
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/controller/dto/UserProfileResponse.java
  src/main/java/com/spaceclub/user/controller/dto/UserProfileUpdateRequest.java
  src/main/java/com/spaceclub/user/controller/dto/UserRequiredInfoRequest.java
  src/main/java/com/spaceclub/user/domain/Email.java
  src/main/java/com/spaceclub/user/domain/User.java
  src/main/java/com/spaceclub/user/service/UserService.java
  src/main/java/com/spaceclub/user/service/vo/RequiredProfile.java
  src/main/java/com/spaceclub/user/service/vo/UserProfile.java
  src/test/java/com/spaceclub/club/controller/ClubEventControllerTest.java
  src/test/java/com/spaceclub/user/controller/LoginControllerTest.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
  src/test/java/com/spaceclub/user/domain/UserTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: FEAT

#274 [SKRB-355] feat: 회원 가입 시 웰컴 이메일 보내는 기능 구현
  src/main/java/com/spaceclub/global/config/CustomAsyncExceptionHandler.java
  src/main/java/com/spaceclub/global/mail/MailEvent.java
  src/main/java/com/spaceclub/global/mail/MailService.java
  src/main/java/com/spaceclub/user/controller/UserController.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/main/java/com/spaceclub/user/service/vo/RequiredProfile.java
  src/test/java/com/spaceclub/user/controller/UserControllerTest.java
Labels: FEAT

#281 hotfix: 토큰 만료 예외와 형식이 잘못되었을때 예외 분리
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/global/exception/GlobalExceptionCode.java
  src/main/java/com/spaceclub/global/interceptor/AuthorizationInterceptor.java
  src/main/java/com/spaceclub/global/interceptor/JwtAuthenticationProvider.java
  src/main/java/com/spaceclub/global/jwt/Jwt.java
Labels: bug, FEAT

#275 fix: 이미지 max size 초과시 예외메세지 code로 변경
  src/main/java/com/spaceclub/global/exception/advice/ControllerAdvice.java
Labels: bug, FEAT

#282 hotfix: 테스트 위한 유저 삭제 설정 변경
  src/main/java/com/spaceclub/user/service/AccountDeleteScheduler.java
Labels: enhancement

#284 fix: 리프레시 토큰 및 엑세스 토큰 만료 예외 분리
  src/docs/asciidoc/exception-api.adoc
  src/main/java/com/spaceclub/global/exception/GlobalExceptionCode.java
  src/main/java/com/spaceclub/global/jwt/Jwt.java
  src/main/java/com/spaceclub/global/jwt/JwtManager.java
Labels: bug, FEAT

#287 fix: 행사 수정 api의 formDate관련 수정
  src/main/java/com/spaceclub/event/controller/dto/EventUpdateRequest.java
Labels: bug

#288 fix: 클럽 삭제 시 행사가 삭제 안되는 문제 해결
  src/main/java/com/spaceclub/club/service/ClubService.java
  src/main/java/com/spaceclub/event/repository/EventRepository.java
  src/main/java/com/spaceclub/event/service/EventProvider.java
  src/main/java/com/spaceclub/event/service/EventService.java
Labels: bug

#291 feat: cors 설정에 refresh token를 exposed header에 추가
  src/main/java/com/spaceclub/global/config/WebConfig.java
Labels: FEAT

#295 chore: 발표를 위한 엑세스토큰 / 리프레시 토큰 시간 변경
  src/main/resources/application-develop.yml
Labels: FEAT

#293 feat: 금칙어 적용시 어노테이션 통해 validation 하는 기능 추가
  build.gradle
  src/main/java/com/spaceclub/club/controller/dto/ClubUpdateRequest.java
  src/main/java/com/spaceclub/global/bad_word_filter/BadWord.java
  src/main/java/com/spaceclub/global/bad_word_filter/BadWordFilter.java
Labels: FEAT

#294 feat: mail 패키지 notification 아래 새로운 패키지로 분리
  src/main/java/com/spaceclub/notification/mail/EmailConfig.java
  src/main/java/com/spaceclub/notification/mail/HtmlConverter.java
  src/main/java/com/spaceclub/notification/mail/MailEvent.java
  src/main/java/com/spaceclub/notification/mail/MailInfo.java
  src/main/java/com/spaceclub/notification/mail/MailProperties.java
  src/main/java/com/spaceclub/notification/mail/MailService.java
  src/main/java/com/spaceclub/notification/mail/domain/MailTracker.java
  src/main/java/com/spaceclub/notification/mail/repository/MailTrackerRepository.java
  src/main/java/com/spaceclub/user/service/AccountService.java
Labels: FEAT

#297 feat: markdown 의존성 제거
  build.gradle
  src/main/java/com/spaceclub/notification/mail/HtmlConverter.java
  src/main/java/com/spaceclub/notification/mail/MailEvent.java
  src/main/java/com/spaceclub/notification/mail/MailInfo.java
  src/main/java/com/spaceclub/notification/mail/MailService.java
  src/main/java/com/spaceclub/notification/mail/domain/MailTracker.java
  src/main/java/com/spaceclub/notification/mail/domain/Template.java
  src/main/resources/static/markdown/test.md
  src/main/resources/static/markdown/welcome.md
  src/main/resources/templates/index.html
Labels: FEAT, REFACTOR

#299 chore: CODEOWNERS 삭제
  .github/CODEOWNERS
Labels: wontfix

#298 feat: 메일 발송 실패에 대한 fallback - 재전송 api 기능 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/notification-api.adoc
  src/main/java/com/spaceclub/notification/mail/MailEvent.java
  src/main/java/com/spaceclub/notification/mail/MailInfo.java
  src/main/java/com/spaceclub/notification/mail/MailProperties.java
  src/main/java/com/spaceclub/notification/mail/controller/MailController.java
  src/main/java/com/spaceclub/notification/mail/domain/MailTracker.java
  src/main/java/com/spaceclub/notification/mail/domain/Template.java
  src/main/java/com/spaceclub/notification/mail/repository/MailTrackerRepository.java
  src/main/java/com/spaceclub/notification/mail/service/MailRetryService.java
  src/main/java/com/spaceclub/notification/mail/service/MailService.java
  src/main/resources/application.yml
  src/main/resources/templates/welcome.html
  src/test/java/com/spaceclub/club/controller/ClubUserControllerTest.java
  src/test/java/com/spaceclub/notification/mail/controller/MailControllerTest.java
Labels: FEAT

#300 feat: 스페이스 클럽 메일 시스템 구현
  src/main/java/com/spaceclub/form/service/SubmitService.java
  src/main/java/com/spaceclub/global/config/ThymeleafConfig.java
  src/main/java/com/spaceclub/notification/mail/MailEvent.java
  src/main/java/com/spaceclub/notification/mail/MailInfo.java
  src/main/java/com/spaceclub/notification/mail/domain/AdditionalInfo.java
  src/main/java/com/spaceclub/notification/mail/domain/MailTracker.java
  src/main/java/com/spaceclub/notification/mail/domain/Template.java
  src/main/java/com/spaceclub/notification/mail/repository/TemplateRepository.java
  src/main/java/com/spaceclub/notification/mail/service/ContextCreator.java
  src/main/java/com/spaceclub/notification/mail/service/MailService.java
  src/main/java/com/spaceclub/notification/mail/service/event/MailEvent.java
  src/main/java/com/spaceclub/notification/mail/service/vo/EventStatusChangeMailInfo.java
  src/main/java/com/spaceclub/notification/mail/service/vo/MailInfo.java
  src/main/java/com/spaceclub/notification/mail/service/vo/ParticipationStatus.java
  src/main/java/com/spaceclub/notification/mail/service/vo/Template.java
  src/main/java/com/spaceclub/notification/mail/service/vo/WelcomeMailInfo.java
  src/main/java/com/spaceclub/user/service/AccountService.java
  src/main/resources/templates/welcome.html
  src/test/java/com/spaceclub/notification/mail/repository/TemplateRepositoryTest.java
Labels: FEAT, REFACTOR

#302 [SKRR-3] feat: 게시판 api 명세 및 Rest Docs 문서화
  src/docs/asciidoc/board-api.adoc
  src/docs/asciidoc/board/comment-api.adoc
  src/docs/asciidoc/board/post-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user/bookmark-api.adoc
  src/main/java/com/spaceclub/board/controller/CommentController.java
  src/main/java/com/spaceclub/board/controller/PostController.java
  src/main/java/com/spaceclub/board/controller/domain/Comment.java
  src/main/java/com/spaceclub/board/controller/domain/Post.java
  src/main/java/com/spaceclub/board/controller/dto/CommentRequest.java
  src/main/java/com/spaceclub/board/controller/dto/CommentResponse.java
  src/main/java/com/spaceclub/board/controller/dto/PostRequest.java
  src/main/java/com/spaceclub/board/controller/dto/PostResponse.java
  src/main/java/com/spaceclub/board/service/BoardService.java
  src/main/java/com/spaceclub/global/BaseTimeEntity.java
  src/main/java/com/spaceclub/global/dto/SliceResponse.java
  src/test/java/com/spaceclub/board/controller/CommentControllerTest.java
  src/test/java/com/spaceclub/board/controller/PostControllerTest.java
Labels: documentation, FEAT
